### ISSUE TITLE
Correo cambio de estado en asesoría

### ISSUE THREAD

**Issue by Jvviers** [Jvviers/Proyecto_Laboratorio#29]
El envío del correo en el cambio de estado "agendado" en asesoría no lo reconoce, esto es debido a que existe otro estado llamado Agendado, por lo que supongo que se "confunde". Probé cambiándole el nombre y más. Queda para revisión.

**Comment by Nicolas-Cuadra** [comment]
Ya se usa el mismo nombre "Agendado"
